version: '3.3'
services:
  nginx:
    image: nginx:1.13.6
    restart: always
    volumes:
      - .:/var/www/html/watchpoint-io
      - ./docker/nginx/watchpoint.conf:/etc/nginx/conf.d/watchpoint.conf
    ports:
      - 80
    depends_on:
      - php-fpm

  php-fpm:
    image: php:7.1.11-fpm-jessie
    restart: always
    volumes:
      - .:/var/www/html/watchpoint-io
    ports:
      - 9000
